### ISSUE TITLE
你好  runloop原理机制

### ISSUE THREAD

**Issue by MoShenGuo** [wuyunfeng/LightWeightRunLoop#2]
能解释一下这个具体是干什么吗?有点看不懂,我是从YY作者看到你介绍来的

**Comment by MoShenGuo** [comment]
好

**Comment by wuyunfeng** [comment]
@MoShenGuo 这个就是实现了iOS/MACOS 的Runloop，并且实现了几个和runloop相关的API，在于帮助大家理解runloop的本质，能够更好的应用runloop以及做一些优化操作
